name: Deploy Webapp to GitHub Pages
on:
  push:
    branches: [main]
    paths:
      - \"webapp/**\"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: \"pages\"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: \"18\"
          cache: \"npm\"
          cache-dependency-path: webapp/package-lock.json
      - uses: actions/configure-pages@v4
      - run: npm ci
        working-directory: ./webapp
      - run: npm run build
        working-directory: ./webapp
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./webapp/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
